config/routes.rb
Rails.application.routes.draw do
  scope :admin do
    resources :questionnaires, only: [:index, :create, :show, :new]
    resources :members, except: [:show], param: :url
    post "members/creates" => "members#creates"
  end
  resources :answers, only: [:show, :update], param: :url
  resources :members, only: [:show, :update, :edit], param: :url
  root to: "answers#home"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :member
  belongs_to :questionnaire
  validates :url, presence: true, uniqueness: true

  def is_bool?
    question_type == "Bool"
  end

  def self.get_hex
      while self.find_by(url: (hex = SecureRandom.hex)) do end
      hex
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true

  def view_for_select
    "#{note}; #{name}; (#{email})"
  end
end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
  has_many :answers
  has_many :members, through: :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :update]

  # GET /answers/1
  # GET /answers/1.json
  def show
    @title = @answer.question
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    if @answer.update(answer_params)
      render :exit
    else
      render plain: "Error occured."
    end
  end

  def home
    render plain: "#{APPNAME} へようこそ！"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find_by(url: params[:url])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:reply)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :answer_path
  before_filter :authenticate

  def answer_path(obj)
    if obj.is_a?(Answer)
      super(obj.url)
    else
      super(obj)
    end
  end

  private
    def authenticate
      return true unless request.path_info.include?("/admin/")
      authenticate_or_request_with_http_basic do |user, pass|
        user = LOGIN
        pass = LOGINPASS
      end
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.order("note DESC")
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    @member.url = get_hex

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def creates
    Member.transaction do
      member_creates_params[:lines].split(/[\r\n]+/).each do |line|
        line_params = line.split(/\t/)
        Member.new({
          name: line_params[0],
          name_kana: line_params[1],
          section: line_params[2],
          note: line_params[3],
          email: line_params[4],
          url: get_hex
        }).save
      end
    end
    redirect_to members_path
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :name_kana, :section, :note, :email, :url)
    end

    def member_creates_params
      params.permit(:lines)
    end

    def get_hex
      while Member.find_by(url: (hex = SecureRandom.hex)) do end
      hex
    end
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: [:show, :edit, :update, :destroy]

  # GET /questionnaires
  # GET /questionnaires.json
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1
  # GET /questionnaires/1.json
  def show
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
  end

  # POST /questionnaires
  # POST /questionnaires.json
  def create
    @questionnaire = Questionnaire.new(questionnaire_params[:questionnaire])

    respond_to do |format|
      if @questionnaire.save
        questionnaire_params[:member_ids].each do |member_id|
          next if member_id == ""
          member = Member.find(member_id)
          content = @questionnaire.content.gsub(/\#\{question\((.*?),(.*?)\)\}/) do
            answer = Answer.new(question: $1, question_type: $2)
            answer.url = Answer.get_hex
            answer.member_id = member.id
            answer.questionnaire_id = @questionnaire.id
            answer.save!
            answer_url(answer.url)
          end
          content = content.gsub(/\#\{name\}/, member.name)
          content = content.gsub(/\#\{email\}/, member.email)
          QuestionnaireMailer.question(member, @questionnaire.subject, content).deliver_later
        end
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questionnaire_params
      params.permit(member_ids: [], questionnaire: [:subject, :content])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    @title ? "#{@title} - #{APPNAME}" : APPNAME
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/answers/exit.html.haml
Thank you.
%input{type: "button", value: "close", "onClick" => "window.close()"}

app/views/answers/show.html.haml
%p
  質問(Question):
  %strong
    = @answer.question
- if @answer.is_bool?
  = form_for(@answer) do |f|
    = f.hidden_field :reply, value: "True"
    = f.submit "はい (Yes)"
  = form_for(@answer) do |f|
    = f.hidden_field :reply, value: "False"
    = f.submit "いいえ (No)"
- else
  = form_for(@answer, url: answer_path(@answer)) do |f|
    = f.text_field :reply
    = f.submit "送信 (Submit)"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/members/_form.html.haml
= form_for(@member) do |f|
  - if @member.errors.any?
    #error_explanation
      %h2
        = pluralize(@member.errors.count, "error")
        prohibited this member from being saved:
      %ul
        - @member.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :name_kana
    %br/
    = f.text_field :name_kana
  .field
    = f.label :section
    %br/
    = f.text_field :section
  .field
    = f.label :note
    %br/
    = f.text_field :note
  .field
    = f.label :email
    %br/
    = f.text_field :url
  .actions
    = f.submit

app/views/members/edit.html.haml
%h1 Editing Member
= render 'form'
= link_to 'Show', @member
|
= link_to 'Back', members_path

app/views/members/index.html.haml
%p#notice= notice
%h1 メンバー一覧
%table
  %thead
    %tr
      %th Name
      %th Name kana
      %th Section
      %th Note
      %th Email
      %th Url
      %th{:colspan => "3"}
  %tbody
    - @members.each do |member|
      %tr
        %td= member.name
        %td= member.name_kana
        %td= member.section
        %td= member.note
        %td= member.email
        %td= member.url
        %td= link_to 'Show', member
        %td= link_to 'Edit', edit_member_path(member)
        %td= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'メンバー作成', new_member_path

app/views/members/new.html.haml
%h1 New Member
%h2 By Person
= render 'form'
%hr
%h2 By TSV
Put them as "Name\tName(kana)\tSection\tNote\temail\n"
= form_tag members_creates_path do
  = text_area_tag :lines
  = submit_tag "送信"
= link_to 'Back', members_path

app/views/members/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @member.name
%p
  %strong Name kana:
  = @member.name_kana
%p
  %strong Section:
  = @member.section
%p
  %strong Note:
  = @member.note
%p
  %strong Email:
  = @member.email
%p
  %strong Url:
  = @member.url
= link_to 'Edit', edit_member_path(@member)
|
= link_to 'Back', members_path

app/views/questionnaires/index.html.haml
%p#notice= notice
%h1 Listing Questionnaires
%table
  %thead
    %tr
      %th Subject
      %th Content
      %th{:colspan => "2"}
  %tbody
    - @questionnaires.each do |questionnaire|
      %tr
        %td= questionnaire.subject
        %td= questionnaire.content
        %td= link_to 'Show', questionnaire
        %td= link_to 'Destroy', questionnaire, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Questionnaire', new_questionnaire_path

app/views/questionnaires/new.html.haml
%h1 New Questionnaire
= form_for(@questionnaire) do |f|
  %p
    = f.label "subject"
    = f.text_field :subject
  %p
    = f.label "content"
    = f.text_area :content
  %p
    = f.label "送信先（複数）"
    = f.collection_select(:member_ids, Member.order("note DESC"), :id, :view_for_select, {}, {multiple: true, name: "member_ids[]", size: 20})
  = f.submit "送信"
= link_to 'Back', questionnaires_path

app/views/questionnaires/show.html.haml
%p#notice= notice
%p
  %strong Subject:
  = @questionnaire.subject
%p
  %strong Content:
  = @questionnaire.content
%p
  - @questionnaire.answers.each do |answer|
    = answer.member.name
    = answer.question_type
    = answer.question
    = answer.reply
= link_to 'Back', questionnaires_path